#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker7"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "4541611b42c54ac9838758e1007d9fc3" }
]

[assets]
directory = "./public"
